config/routes.rb
WsWeb::Application.routes.draw do

  root to: "static_pages#home"

  match '/products',  to:   "static_pages#products"
  match "/services",  to:   "static_pages#services"
  match "/wiki",      to:   "static_pages#wiki"
  match "/about",     to:   "static_pages#about"

  match "/contact",   to:   "contact#new"

  match "/signup",    to:   "users#new"

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  company    :string(255)
#  address1   :string(255)
#  address2   :string(255)
#  zipcode    :string(255)
#  town       :string(255)
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  email      :string(255)
#

class Contact < ActiveRecord::Base
  attr_accessible :address1, :address2, :email, :comment, :company, :name, :town, :zipcode
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  gravatar   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :gravatar, :name

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def products
  end

  def services
  end

  def wiki
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Work-smarter.nl"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/new.html.erb
<% provide(:title, 'Contact') %>
<h1>Neem contact op</h1>
<p>contact formulier</p>

app/views/layouts/_footer.html.erb
      <div class="footer">
        <p>&copy; Work-smarter.nl (c) 2013</p>
      </div>

app/views/layouts/_javafooter.html.erb
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

app/views/layouts/_navblok.html.erb
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Producten", products_path %></li>
                <li><%= link_to "Diensten", services_path %></li>
                <li><%= link_to "Wiki", wiki_path %></li>
                <li><%= link_to "Over ons", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
 <body>

    <div class="container">

      <div class="masthead">
        <h3 class="muted">Work-smarter.nl</h3>
        <%= render 'layouts/navblok' %>
      </div>

			<%= yield %>

      <hr>
      <%= render 'layouts/footer' %>

    </div> <!-- /container -->
    <%= render 'layouts/javafooter' %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Over ons') %>
<h1>Over Work-smarter</h1>
<p>Work-smarter is zowel een eenmanszaak als een samenwerkingsverband van zzp-ers die samen oplossingen willen bieden aan bedrijven. Door deze opzet kan Work-smarter (als hoofdaannemer) voor elk project of uitdaging de juiste professionals leveren. Wij committeren ons aan het resultaat, niet aan de inzet.

<h3>Rik Megens</h3>
<ul>
	<li><img=http://www.gravatar.com/avatar/516705f396580a3b8a46b54a4be0f364.png /></li>
	<li>faq sheet</li>
</ul>
<h3>Peter Creyghton</h3>
<ul>
	<li>gravatar van Peter</li>
	<li>faq sheet</li>
</ul>

<p>Voor ZZP-ers: ook meedoen aan dit netwerk ? Dat kan! Neem contact op via de contact pagina en vermeld in de onderwerp 'Meedoen'
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Contactgegevens</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Work-smarter ontwart ontzorgt</h1>
        <p class="lead">Work smarter neemt verantwoordelijkheid voor de beschikbaarheid van uw ICT behoeften</p>
        <%= link_to "Neem vandaag contact op!", contact_path, class: "btn btn-large btn-success"%>
      </div>

      <hr>

      <div class="row-fluid">
        <div class="span6">
          <h2>Ontwarren</h2>
          <p>Bij <strong>Onwarren</strong> wordt gekeken naar de huidige stand van de IT. Alles wordt hierbij beschreven. Het resultaat is een compleet beeld, waarin duidelijk gemaakt is waar de doublures zitten en waar de gaten. </p>
          <p><a class="btn" href="#">Lees meer &raquo;</a></p>
        </div>
        <!--
        <div class="span2">
        </div>
      -->
        <div class="span6">
          <h2>Ontzorgen</h2>
          <p>Bij <strong>Ontzorgen</strong> worden de organisatorische aspecten in kaart gebracht. Na het toewijzen van deze taken aan mensen of leveranciers worden deze afspraken samengebracht in een Dossier Afspraken en Procedures(DAP) of een Service Level Agreement (SLA).  </p>
          <p><a class="btn" href="#">Lees meer &raquo;</a></p>
       </div>
      </div>

app/views/static_pages/products.html.erb
<% provide(:title, 'Producten') %>
<h1>Onze producten</h1>
<h3>InstantCloud</h3>
<p>
Voor bedrijven die willen testen wat cloud computing voor hun zou kunnen betekenen heeft WS de InstantCloud ontworpen. Dit is een fysieke 'black-box' met daarin een virtualisatieplatform (KVM of ESXi), opslagruimte en een virtueel netwerk inclusief een statefull firewall. De InstantCloud kan naast de bestaande IT server voorzieningen neergezet worden. Een stroomkabel en een netwerkkabel naar het bedrijfsnetwerk is voldoende om aan de slag te gaan.
</p>
<p>
Uiteraard levert WS bij InstantCloud 4 uur training aan de bestaande IT beheerders om onmiddellijk met de InstantCloud aan de slag te gaan.
</p>
<p>
InstantCloud kan maximaal 4 weken gebruikt worden voor een vaste prijs van <strong>€ 2500 </strong>(ex btw). 
Hiervoor ontvangt u:
<ul>
<li>4 weken gebruik van de InstantCloud Blackbox</li>
<li>4 uur consultancy mbt Cloud Computing</li>
<li>4 uur ondersteuning bij het opzetten van de testomgeving en testcase(s) </li>
<li>4 weken telefonische ondersteuning tijdens kantooruren</li>
<li>4 uur training onsite voor de IT beheerders </li>
</ul>
</p>
<p>
De omvang van alle bovengenoemde activiteiten wordt ge-time-boxed op de blokken van 4 uur. Met andere woorden, het aantal testcases en de bijbehorende test-omgeving(en) moeten realiseerbaar zijn in 4 uur. Dit hangt in hoge mate af van de volwassenheid van de IT organisatie. Hetzelfde geldt voor de onsite training. Een IT organisatie met veel kennis en ervaring in visualisatie-technieken zal meer en andere zaken leren dan een IT organisatie waar virtualisatie een nieuw concept is. Aan het eind van de 4 uur training zal de eerste organisatie op een ander punt zijn dan de 2e organisatie. 
</p>
<p>
Indien een organisatie meer wil leren over virtualisatie en cloud computing, dan kan hiervoor een additionele afspraak gemaakt worden.
</p>

app/views/static_pages/services.html.erb
<% provide(:title, 'Diensten') %>
<h1>Over onze Services</h1>
Work-smarter heeft ruime ervaring in :
<ul>
	<li>virtualiseren van de bestaande kantoor automatisering</li>
	<li>ontwerpen en bouwen van nieuwe kantoor automatisering</li>
	<li>ontwerpen en bouwen van een hosted infrastructuur (private cloud)</li>
	<li>migratie en projectmanagent naar de public cloud</li>
	<li>beheer van uw serveromgeving</li>
	<li>beheer van uw kantooratomatisering-omgeving</li>
	<li>ondersteuning bij inkoop van ICT producten en diensten</li>
	<li>interim management van uw ICT afdeling</li>
</ul>

app/views/static_pages/wiki.html.erb
<% provide(:title, 'Wiki') %>
<h1>Wiki</h1>
<p>Op deze wiki worden (technische) onderwerpen vastgelegd die ik dagelijks tegenkom om tegengekomen ben. Als zodanig is de wiki een 'brain-dump' met mijn persoonlijke ervaringen (goed en minder goed). De gekozen oplossingen zijn 'mijn' gekozen oplossingen. Dit zijn niet noodzakelijkerwijs de 'beste' oplossingen. Voor de 'beste' oplossingen verwijs ik graag naar <a href="http://www.google.nl">hier</a></p>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Sign up</h1>
<p>Aanmelden</p>